send req

get http://localhost:3004/

send req

post http://localhost:3004/user
Content-Type: application/json
{
    "name":"sondharya",
    "username":"soVfjvbfd",
    "password" : "13345454",
     "gender":"female",
     "location":"bangalore"

}
